-- Fluent — Prolog: słówka i zwroty z przekazanego fragmentu
-- Wygenerowane przez import/seed-study-pack.mjs — nie edytuj ręcznie.
-- 423 haseł. Wklej całość do edytora SQL w Supabase i uruchom.
--
-- Skrypt jest idempotentny: hasło o tym samym lemacie i tej samej części mowy
-- nie zostanie dodane po raz drugi ani nadpisane.

begin;

create temporary table fluent_study_pack (
  lemma           text not null,
  display         text not null,
  article         text,
  word_type       text not null,
  gender          text,
  translation_pl  text,
  example_de      text,
  example_pl      text,
  cefr            text,
  source          text,
  topic           text,
  plural          text,
  aux             text,
  synonyms        text[],
  ipa             text
) on commit drop;

insert into fluent_study_pack (lemma, display, article, word_type, gender, translation_pl, example_de, example_pl, cefr, source, topic, plural, aux, synonyms, ipa) values
  ('Wald'::text, 'der Wald'::text, 'der'::text, 'noun'::text, 'm'::text, 'las'::text, null::text, null::text, null::text, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16'::text, null::text, 'Wälder'::text, null::text, null::text[], null::text),
  ('Wildling', 'der Wildling', 'der', 'noun', 'm', 'dziki / człowiek żyjący poza cywilizacją', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Wildlinge', null, null, null),
  ('Tote', 'der Tote', 'der', 'noun', 'm', 'zmarły / umarły', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Toten', null, null, null),
  ('Angst', 'die Angst', 'die', 'noun', 'f', 'strach / lęk', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Ängste', null, null, null),
  ('Anflug', 'der Anflug', 'der', 'noun', 'm', 'ślad / cień / ledwie dostrzegalna oznaka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Anflüge', null, null, null),
  ('Lächeln', 'das Lächeln', 'das', 'noun', 'n', 'uśmiech', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Lächeln', null, null, null),
  ('Mann', 'der Mann', 'der', 'noun', 'm', 'mężczyzna / człowiek', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Männer', null, null, null),
  ('Lord', 'der Lord', 'der', 'noun', 'm', 'lord', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Lords', null, null, null),
  ('Sache', 'die Sache', 'die', 'noun', 'f', 'sprawa / rzecz', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Sachen', null, null, null),
  ('Beweis', 'der Beweis', 'der', 'noun', 'm', 'dowód', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Beweise', null, null, null),
  ('Streit', 'der Streit', 'der', 'noun', 'm', 'kłótnia / spór', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Streite / Streitigkeiten', null, null, null),
  ('Mutter', 'die Mutter', 'die', 'noun', 'f', 'matka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Mütter', null, null, null),
  ('Lied', 'das Lied', 'das', 'noun', 'n', 'piosenka / pieśń', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Lieder', null, null, null),
  ('Amme', 'die Amme', 'die', 'noun', 'f', 'mamka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Ammen', null, null, null),
  ('Zitze', 'die Zitze', 'die', 'noun', 'f', 'sutek / brodawka sutkowa', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Zitzen', null, null, null),
  ('Frau', 'die Frau', 'die', 'noun', 'f', 'kobieta / żona', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Frauen', null, null, null),
  ('Stimme', 'die Stimme', 'die', 'noun', 'f', 'głos', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Stimmen', null, null, null),
  ('Ritt', 'der Ritt', 'der', 'noun', 'm', 'jazda konna / podróż konno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Ritte', null, null, null),
  ('Tag', 'der Tag', 'der', 'noun', 'm', 'dzień', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Tage', null, null, null),
  ('Nacht', 'die Nacht', 'die', 'noun', 'f', 'noc', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Nächte', null, null, null),
  ('Himmel', 'der Himmel', 'der', 'noun', 'm', 'niebo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Himmel', null, null, null),
  ('Zeit', 'die Zeit', 'die', 'noun', 'f', 'czas / pora', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Zeiten', null, null, null),
  ('Dunkelheit', 'die Dunkelheit', 'die', 'noun', 'f', 'ciemność / mrok', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Manneskraft', 'die Manneskraft', 'die', 'noun', 'f', 'męska siła / wigor', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Zug', 'der Zug', 'der', 'noun', 'm', 'pociąg / ruch / rys twarzy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Züge', null, null, null),
  ('Mund', 'der Mund', 'der', 'noun', 'm', 'usta', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Münder', null, null, null),
  ('Zorn', 'der Zorn', 'der', 'noun', 'm', 'gniew', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Auge', 'das Auge', 'das', 'noun', 'n', 'oko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Augen', null, null, null),
  ('Kapuze', 'die Kapuze', 'die', 'noun', 'f', 'kaptur', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Kapuzen', null, null, null),
  ('Umhang', 'der Umhang', 'der', 'noun', 'm', 'płaszcz / peleryna', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Umhänge', null, null, null),
  ('Jahr', 'das Jahr', 'das', 'noun', 'n', 'rok', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Jahre', null, null, null),
  ('Nachtwache', 'die Nachtwache', 'die', 'noun', 'f', 'nocna warta / nocna straż', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Nachtwachen', null, null, null),
  ('Junge', 'der Junge', 'der', 'noun', 'm', 'chłopiec', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Jungen', null, null, null),
  ('Stolz', 'der Stolz', 'der', 'noun', 'm', 'duma', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Anspannung', 'die Anspannung', 'die', 'noun', 'f', 'napięcie / spięcie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Anspannungen', null, null, null),
  ('Unbehagen', 'das Unbehagen', 'das', 'noun', 'n', 'niepokój / dyskomfort', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Mauer', 'die Mauer', 'die', 'noun', 'f', 'mur', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Mauern', null, null, null),
  ('Mal', 'das Mal', 'das', 'noun', 'n', 'raz / okazja', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Male', null, null, null),
  ('Seite', 'die Seite', 'die', 'noun', 'f', 'strona', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Seiten', null, null, null),
  ('Geschichte', 'die Geschichte', 'die', 'noun', 'f', 'historia / opowieść', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Geschichten', null, null, null),
  ('Herz', 'das Herz', 'das', 'noun', 'n', 'serce', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Herzen', null, null, null),
  ('Hose', 'die Hose', 'die', 'noun', 'f', 'spodnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Hosen', null, null, null),
  ('Veteran', 'der Veteran', 'der', 'noun', 'm', 'weteran', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Veteranen', null, null, null),
  ('Patrouille', 'die Patrouille', 'die', 'noun', 'f', 'patrol', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Patrouillen', null, null, null),
  ('Wildnis', 'die Wildnis', 'die', 'noun', 'f', 'dzicz / bezludne pustkowie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Südländer', 'der Südländer', 'der', 'noun', 'm', 'człowiek z południa / południowiec', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Südländer', null, null, null),
  ('Abend', 'der Abend', 'der', 'noun', 'm', 'wieczór', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Abende', null, null, null),
  ('Schärfe', 'die Schärfe', 'die', 'noun', 'f', 'ostrość / przenikliwość', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Finsternis', 'die Finsternis', 'die', 'noun', 'f', 'mrok / głęboka ciemność', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Finsternisse', null, null, null),
  ('Nackenhaar', 'das Nackenhaar', 'das', 'noun', 'n', 'włos na karku', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Nackenhaare', null, null, null),
  ('Norden', 'der Norden', 'der', 'noun', 'm', 'północ', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Nordwesten', 'der Nordwesten', 'der', 'noun', 'm', 'północny zachód', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Ferse', 'die Ferse', 'die', 'noun', 'f', 'pięta', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Fersen', null, null, null),
  ('Bande', 'die Bande', 'die', 'noun', 'f', 'banda / grupa', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Banden', null, null, null),
  ('Plünderer', 'der Plünderer', 'der', 'noun', 'm', 'grabieżca / łupieżca', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Plünderer', null, null, null),
  ('Wind', 'der Wind', 'der', 'noun', 'm', 'wiatr', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Winde', null, null, null),
  ('Baum', 'der Baum', 'der', 'noun', 'm', 'drzewo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Bäume', null, null, null),
  ('Schutz', 'der Schutz', 'der', 'noun', 'm', 'ochrona / schronienie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Vorgesetzte', 'der Vorgesetzte', 'der', 'noun', 'm', 'przełożony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Vorgesetzten', null, null, null),
  ('Sohn', 'der Sohn', 'der', 'noun', 'm', 'syn', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Söhne', null, null, null),
  ('Geschlecht', 'das Geschlecht', 'das', 'noun', 'n', 'płeć / ród', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Geschlechter', null, null, null),
  ('Erbe', 'der Erbe', 'der', 'noun', 'm', 'spadkobierca / dziedzic', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Erben', null, null, null),
  ('Klinge', 'die Klinge', 'die', 'noun', 'f', 'ostrze / klinga', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Klingen', null, null, null),
  ('Streitross', 'das Streitross', 'das', 'noun', 'n', 'rumak bojowy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Streitrösser', null, null, null),
  ('Ritter', 'der Ritter', 'der', 'noun', 'm', 'rycerz', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Ritter', null, null, null),
  ('Klepper', 'der Klepper', 'der', 'noun', 'm', 'szkapa / mizerny koń', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Klepper', null, null, null),
  ('Lederstiefel', 'der Lederstiefel', 'der', 'noun', 'm', 'skórzany but z cholewą', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Lederstiefel', null, null, null),
  ('Wollhose', 'die Wollhose', 'die', 'noun', 'f', 'wełniane spodnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Wollhosen', null, null, null),
  ('Hirschlederhandschuh', 'der Hirschlederhandschuh', 'der', 'noun', 'm', 'rękawiczka z jeleniej skóry', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Hirschlederhandschuhe', null, null, null),
  ('Hemd', 'das Hemd', 'das', 'noun', 'n', 'koszula', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Hemden', null, null, null),
  ('Kette', 'die Kette', 'die', 'noun', 'f', 'łańcuch / łańcuszek', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Ketten', null, null, null),
  ('Schicht', 'die Schicht', 'die', 'noun', 'f', 'warstwa / zmiana robocza', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Schichten', null, null, null),
  ('Wolle', 'die Wolle', 'die', 'noun', 'f', 'wełna', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Leder', 'das Leder', 'das', 'noun', 'n', 'skóra wyprawiona / materiał skórzany', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Bruder', 'der Bruder', 'der', 'noun', 'm', 'brat', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Brüder', null, null, null),
  ('Berufung', 'die Berufung', 'die', 'noun', 'f', 'powołanie / wezwanie do funkcji', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Berufungen', null, null, null),
  ('Garderobe', 'die Garderobe', 'die', 'noun', 'f', 'garderoba / ubiór', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Garderoben', null, null, null),
  ('Krönung', 'die Krönung', 'die', 'noun', 'f', 'koronacja / ukoronowanie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Krönungen', null, null, null),
  ('Zobel', 'der Zobel', 'der', 'noun', 'm', 'soból / futro sobolowe', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Zobel', null, null, null),
  ('Sünde', 'die Sünde', 'die', 'noun', 'f', 'grzech', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Sünden', null, null, null),
  ('Kaserne', 'die Kaserne', 'die', 'noun', 'f', 'koszary', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Kasernen', null, null, null),
  ('Wein', 'der Wein', 'der', 'noun', 'm', 'wino', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Weine', null, null, null),
  ('Biest', 'das Biest', 'das', 'noun', 'n', 'bestia / paskudne stworzenie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Biester', null, null, null),
  ('Hals', 'der Hals', 'der', 'noun', 'm', 'szyja / gardło', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Hälse', null, null, null),
  ('Krieger', 'der Krieger', 'der', 'noun', 'm', 'wojownik', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Krieger', null, null, null),
  ('Lachen', 'das Lachen', 'das', 'noun', 'n', 'śmiech', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Befehl', 'der Befehl', 'der', 'noun', 'm', 'rozkaz', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Befehle', null, null, null),
  ('Glas', 'das Glas', 'das', 'noun', 'n', 'szkło / szklanka / kieliszek', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Gläser', null, null, null),
  ('Ärger', 'der Ärger', 'der', 'noun', 'm', 'kłopot / złość / przykrość', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Wetter', 'das Wetter', 'das', 'noun', 'n', 'pogoda', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Rückweg', 'der Rückweg', 'der', 'noun', 'm', 'droga powrotna', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Rückwege', null, null, null),
  ('Woche', 'die Woche', 'die', 'noun', 'f', 'tydzień', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Wochen', null, null, null),
  ('Schnee', 'der Schnee', 'der', 'noun', 'm', 'śnieg', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Eissturm', 'der Eissturm', 'der', 'noun', 'm', 'burza lodowa / nawałnica z marznącym opadem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Eisstürme', null, null, null),
  ('Herr', 'der Herr', 'der', 'noun', 'm', 'pan / władca', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Herren', null, null, null),
  ('Dämmerung', 'die Dämmerung', 'die', 'noun', 'f', 'zmierzch / świt / półmrok', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Dämmerungen', null, null, null),
  ('Art', 'die Art', 'die', 'noun', 'f', 'rodzaj / sposób', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Arten', null, null, null),
  ('Weise', 'die Weise', 'die', 'noun', 'f', 'sposób / maniera', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Weisen', null, null, null),
  ('Einzelheit', 'die Einzelheit', 'die', 'noun', 'f', 'szczegół', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Einzelheiten', null, null, null),
  ('Jäger', 'der Jäger', 'der', 'noun', 'm', 'myśliwy / łowca', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Jäger', null, null, null),
  ('Wilderer', 'der Wilderer', 'der', 'noun', 'm', 'kłusownik', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Wilderer', null, null, null),
  ('Reiter', 'der Reiter', 'der', 'noun', 'm', 'jeździec', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Reiter', null, null, null),
  ('Tat', 'die Tat', 'die', 'noun', 'f', 'czyn', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Taten', null, null, null),
  ('Hirsch', 'der Hirsch', 'der', 'noun', 'm', 'jeleń', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Hirsche', null, null, null),
  ('Wahl', 'die Wahl', 'die', 'noun', 'f', 'wybór', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Wahlen', null, null, null),
  ('Schwarz', 'das Schwarz', 'das', 'noun', 'n', 'czerń / czarny kolor', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Hand', 'die Hand', 'die', 'noun', 'f', 'dłoń / ręka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Hände', null, null, null),
  ('Talent', 'das Talent', 'das', 'noun', 'n', 'talent', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Talente', null, null, null),
  ('Lager', 'das Lager', 'das', 'noun', 'n', 'obóz / obozowisko / magazyn', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Lager', null, null, null),
  ('Meile', 'die Meile', 'die', 'noun', 'f', 'mila', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Meilen', null, null, null),
  ('Kamm', 'der Kamm', 'der', 'noun', 'm', 'grzebień / grzbiet górski', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Kämme', null, null, null),
  ('Bach', 'der Bach', 'der', 'noun', 'm', 'strumień / potok', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Bäche', null, null, null),
  ('Kind', 'das Kind', 'das', 'noun', 'n', 'dziecko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Kinder', null, null, null),
  ('Fels', 'der Fels', 'der', 'noun', 'm', 'skała', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Felsen', null, null, null),
  ('Unterstand', 'der Unterstand', 'der', 'noun', 'm', 'schronienie / wiata', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Unterstände', null, null, null),
  ('Feuer', 'das Feuer', 'das', 'noun', 'n', 'ogień / ognisko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Feuer', null, null, null),
  ('Feuerstelle', 'die Feuerstelle', 'die', 'noun', 'f', 'palenisko / miejsce na ognisko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Feuerstellen', null, null, null),
  ('Lebende', 'der Lebende', 'der', 'noun', 'm', 'żywy człowiek', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Lebenden', null, null, null),
  ('Blut', 'das Blut', 'das', 'noun', 'n', 'krew', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Waffe', 'die Waffe', 'die', 'noun', 'f', 'broń / sztuka broni', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Waffen', null, null, null),
  ('Schwert', 'das Schwert', 'das', 'noun', 'n', 'miecz', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Schwerter', null, null, null),
  ('Bogen', 'der Bogen', 'der', 'noun', 'm', 'łuk', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Bögen', null, null, null),
  ('Axt', 'die Axt', 'die', 'noun', 'f', 'siekiera / topór', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Äxte', null, null, null),
  ('Stück', 'das Stück', 'das', 'noun', 'n', 'kawałek / sztuka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Stücke', null, null, null),
  ('Eisen', 'das Eisen', 'das', 'noun', 'n', 'żelazo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Leiche', 'die Leiche', 'die', 'noun', 'f', 'zwłoki / ciało zmarłego', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Leichen', null, null, null),
  ('Achsel', 'die Achsel', 'die', 'noun', 'f', 'pacha', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Achseln', null, null, null),
  ('Stein', 'der Stein', 'der', 'noun', 'm', 'kamień', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Steine', null, null, null),
  ('Boden', 'der Boden', 'der', 'noun', 'm', 'ziemia / podłoże / podłoga', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Böden', null, null, null),
  ('Eisenholz', 'das Eisenholz', 'das', 'noun', 'n', 'drzewo żelazne / bardzo twarde drewno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Eisenhölzer', null, null, null),
  ('Zweig', 'der Zweig', 'der', 'noun', 'm', 'gałąź / gałązka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Zweige', null, null, null),
  ('Blick', 'der Blick', 'der', 'noun', 'm', 'spojrzenie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Blicke', null, null, null),
  ('Schauer', 'der Schauer', 'der', 'noun', 'm', 'dreszcz / przelotny opad', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Schauer', null, null, null),
  ('Rücken', 'der Rücken', 'der', 'noun', 'm', 'plecy / grzbiet', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, 'Rücken', null, null, null),
  ('sollen', 'sollen', null, 'verb', null, 'powinien / mieć coś zrobić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('umkehren', 'umkehren', null, 'verb', null, 'zawrócić / wrócić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('drängen', 'drängen', null, 'verb', null, 'nalegać / ponaglać / napierać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('dunkeln', 'dunkeln', null, 'verb', null, 'ciemnieć / robić się ciemno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('beginnen', 'beginnen', null, 'verb', null, 'zaczynać / rozpocząć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sein', 'sein', null, 'verb', null, 'być', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('machen', 'machen', null, 'verb', null, 'robić / czynić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('fragen', 'fragen', null, 'verb', null, 'pytać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('lassen', 'lassen', null, 'verb', null, 'pozwalać / zostawiać / sprawiać, że coś się dzieje', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich einlassen', 'sich einlassen', null, 'verb', null, 'wdawać się / dać się wciągnąć / zgadzać się na coś', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('haben', 'haben', null, 'verb', null, 'mieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('kommen', 'kommen', null, 'verb', null, 'przychodzić / przybywać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('gehen', 'gehen', null, 'verb', null, 'iść / odchodzić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('sehen', 'sehen', null, 'verb', null, 'widzieć / zobaczyć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sagen', 'sagen', null, 'verb', null, 'mówić / powiedzieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('wissen', 'wissen', null, 'verb', null, 'wiedzieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('werden', 'werden', null, 'verb', null, 'stawać się / zostać / czasownik pomocniczy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('hineinziehen', 'hineinziehen', null, 'verb', null, 'wciągać do środka / wciągać w coś', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('lehren', 'lehren', null, 'verb', null, 'uczyć kogoś / nauczać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('singen', 'singen', null, 'verb', null, 'śpiewać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('einwerfen', 'einwerfen', null, 'verb', null, 'wrzucać / wtrącać uwagę', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('erwidern', 'erwidern', null, 'verb', null, 'odpowiadać / odrzec', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('glauben', 'glauben', null, 'verb', null, 'wierzyć / sądzić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('hören', 'hören', null, 'verb', null, 'słyszeć / słuchać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('können', 'können', null, 'verb', null, 'móc / umieć / potrafić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('lernen', 'lernen', null, 'verb', null, 'uczyć się / dowiadywać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('nachhallen', 'nachhallen', null, 'verb', null, 'rozbrzmiewać echem / pobrzmiewać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('erklären', 'erklären', null, 'verb', null, 'wyjaśniać / oznajmiać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('aufsehen', 'aufsehen', null, 'verb', null, 'podnosić wzrok / spoglądać w górę', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('berauben', 'berauben', null, 'verb', null, 'ograbiać / pozbawiać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('erkennen', 'erkennen', null, 'verb', null, 'rozpoznawać / dostrzegać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('gehören', 'gehören', null, 'verb', null, 'należeć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('angehören', 'angehören', null, 'verb', null, 'należeć do organizacji lub grupy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('bemerken', 'bemerken', null, 'verb', null, 'zauważać / dostrzegać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('wittern', 'wittern', null, 'verb', null, 'wyczuwać / węszyć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('teilen', 'teilen', null, 'verb', null, 'dzielić / podzielać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('schicken', 'schicken', null, 'verb', null, 'wysyłać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('einfallen', 'einfallen', null, 'verb', null, 'przychodzić do głowy / przypominać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('rutschen', 'rutschen', null, 'verb', null, 'ślizgać się / ześlizgnąć się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('lachen', 'lachen', null, 'verb', null, 'śmiać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('nennen', 'nennen', null, 'verb', null, 'nazywać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('schrecken', 'schrecken', null, 'verb', null, 'straszyć / przerażać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('liegen', 'liegen', null, 'verb', null, 'leżeć / znajdować się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich sträuben', 'sich sträuben', null, 'verb', null, 'jeżyć się / stawać dęba / wzbraniać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('reiten', 'reiten', null, 'verb', null, 'jechać konno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('wehen', 'wehen', null, 'verb', null, 'wiać / powiewać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('rascheln', 'rascheln', null, 'verb', null, 'szeleścić / szumieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('scheinen', 'scheinen', null, 'verb', null, 'świecić / wydawać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('beobachten', 'beobachten', null, 'verb', null, 'obserwować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('spüren', 'spüren', null, 'verb', null, 'czuć / wyczuwać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('wollen', 'wollen', null, 'verb', null, 'chcieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('anvertrauen', 'anvertrauen', null, 'verb', null, 'powierzać / zwierzać coś komuś', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('aufragen', 'aufragen', null, 'verb', null, 'wznosić się / górować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('tragen', 'tragen', null, 'verb', null, 'nosić / nieść', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('behaupten', 'behaupten', null, 'verb', null, 'twierdzić / utrzymywać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich vorbereiten', 'sich vorbereiten', null, 'verb', null, 'przygotowywać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('angehen', 'angehen', null, 'verb', null, 'dotyczyć / obchodzić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('wetten', 'wetten', null, 'verb', null, 'zakładać się / obstawiać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('meucheln', 'meucheln', null, 'verb', null, 'skrytobójczo mordować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('umdrehen', 'umdrehen', null, 'verb', null, 'odwracać / obracać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('einstimmen', 'einstimmen', null, 'verb', null, 'wtórować / przyłączać się do śpiewu lub śmiechu', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('schwerfallen', 'schwerfallen', null, 'verb', null, 'sprawiać trudność / przychodzić z trudem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('annehmen', 'annehmen', null, 'verb', null, 'przyjmować / uznawać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('müssen', 'müssen', null, 'verb', null, 'musieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('schauen', 'schauen', null, 'verb', null, 'patrzeć / spoglądać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('denken', 'denken', null, 'verb', null, 'myśleć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('zittern', 'zittern', null, 'verb', null, 'drżeć / trząść się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sitzen', 'sitzen', null, 'verb', null, 'siedzieć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('empfinden', 'empfinden', null, 'verb', null, 'odczuwać / czuć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('verfolgen', 'verfolgen', null, 'verb', null, 'śledzić / podążać za kimś / ścigać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('tun', 'tun', null, 'verb', null, 'robić / czynić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('gefallen', 'gefallen', null, 'verb', null, 'podobać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('schneien', 'schneien', null, 'verb', null, 'padać śniegiem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('dauern', 'dauern', null, 'verb', null, 'trwać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich freuen', 'sich freuen', null, 'verb', null, 'cieszyć się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('erleben', 'erleben', null, 'verb', null, 'przeżyć / doświadczyć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('betrachten', 'betrachten', null, 'verb', null, 'przyglądać się / oglądać / rozpatrywać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('herabsinken', 'herabsinken', null, 'verb', null, 'opadać / obniżać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('legen', 'legen', null, 'verb', null, 'kłaść', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('stören', 'stören', null, 'verb', null, 'przeszkadzać / niepokoić', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('dreinblicken', 'dreinblicken', null, 'verb', null, 'spoglądać w określony sposób / mieć określony wyraz twarzy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('erzählen', 'erzählen', null, 'verb', null, 'opowiadać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('auslassen', 'auslassen', null, 'verb', null, 'pomijać / opuszczać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich anschließen', 'sich anschließen', null, 'verb', null, 'przyłączać się / dołączać do', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('ertappen', 'ertappen', null, 'verb', null, 'przyłapać / nakryć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('häuten', 'häuten', null, 'verb', null, 'skórować / obdzierać ze skóry', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('bleiben', 'bleiben', null, 'verb', null, 'zostawać / pozostawać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('anlegen', 'anlegen', null, 'verb', null, 'zakładać / wkładać / tworzyć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('einbüßen', 'einbüßen', null, 'verb', null, 'utracić / postradać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('streifen', 'streifen', null, 'verb', null, 'przemierzać / włóczyć się / muskać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('brauchen', 'brauchen', null, 'verb', null, 'potrzebować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich trauen', 'sich trauen', null, 'verb', null, 'odważyć się / ośmielić się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('bauen', 'bauen', null, 'verb', null, 'budować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('brennen', 'brennen', null, 'verb', null, 'płonąć / palić się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('übersehen', 'übersehen', null, 'verb', null, 'przeoczyć / nie zauważyć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('sich rühren', 'sich rühren', null, 'verb', null, 'ruszać się / poruszać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('einräumen', 'einräumen', null, 'verb', null, 'przyznawać / dopuszczać / wkładać do środka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('aussehen', 'aussehen', null, 'verb', null, 'wyglądać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('achten', 'achten', null, 'verb', null, 'uważać / zwracać uwagę / szanować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('zucken', 'zucken', null, 'verb', null, 'drgnąć / szarpnąć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('lehnen', 'lehnen', null, 'verb', null, 'opierać / być opartym', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('stürzen', 'stürzen', null, 'verb', null, 'upaść / runąć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('schlafen', 'schlafen', null, 'verb', null, 'spać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('vermuten', 'vermuten', null, 'verb', null, 'przypuszczać / domyślać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('beharren', 'beharren', null, 'verb', null, 'upierać się / obstawać przy czymś', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('verbergen', 'verbergen', null, 'verb', null, 'ukrywać / chować', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('lächeln', 'lächeln', null, 'verb', null, 'uśmiechać się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('laufen', 'laufen', null, 'verb', null, 'biec / chodzić / przebiegać', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'sein', null, null),
  ('murmeln', 'murmeln', null, 'verb', null, 'mruczeć / mamrotać / mówić półgłosem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, 'haben', null, null),
  ('tot', 'tot', null, 'other', null, 'martwy / nieżywy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('alt', 'alt', null, 'other', null, 'stary', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('jung', 'jung', null, 'other', null, 'młody', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('leise', 'leise', null, 'other', null, 'cichy / cicho', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('früh', 'früh', null, 'other', null, 'wczesny / wcześnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('spät', 'spät', null, 'other', null, 'późny / późno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('laut', 'laut', null, 'other', null, 'głośny / głośno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dämmrig', 'dämmrig', null, 'other', null, 'pogrążony w półmroku / mroczny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('lang', 'lang', null, 'other', null, 'długi', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('lange', 'lange', null, 'other', null, 'długo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unbeeindruckt', 'unbeeindruckt', null, 'other', null, 'niewzruszony / bez wrażenia', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('angespannt', 'angespannt', null, 'other', null, 'napięty / spięty', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unterdrückt', 'unterdrückt', null, 'other', null, 'tłumiony / stłumiony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dick', 'dick', null, 'other', null, 'gruby', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schwarz', 'schwarz', null, 'other', null, 'czarny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gewohnt', 'gewohnt', null, 'other', null, 'przyzwyczajony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('lustig', 'lustig', null, 'other', null, 'wesoły / zabawny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('verletzt', 'verletzt', null, 'other', null, 'zraniony / urażony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('anders', 'anders', null, 'other', null, 'inaczej', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('anderer', 'anderer', null, 'other', null, 'inny / drugi', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nervös', 'nervös', null, 'other', null, 'nerwowy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gefährlich', 'gefährlich', null, 'other', null, 'niebezpieczny / niebezpiecznie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nah', 'nah', null, 'other', null, 'bliski / blisko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('erste', 'erste', null, 'other', null, 'pierwszy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('endlos', 'endlos', null, 'other', null, 'bezkresny / niekończący się', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('finster', 'finster', null, 'other', null, 'mroczny / ciemny / ponury', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('verflucht', 'verflucht', null, 'other', null, 'przeklęty', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('heutig', 'heutig', null, 'other', null, 'dzisiejszy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('hart', 'hart', null, 'other', null, 'twardy / ciężki / trudny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schlimm', 'schlimm', null, 'other', null, 'zły / okropny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('kalt', 'kalt', null, 'other', null, 'zimny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('lebendig', 'lebendig', null, 'other', null, 'żywy / ożywiony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ganz', 'ganz', null, 'other', null, 'cały', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unerbittlich', 'unerbittlich', null, 'other', null, 'nieubłagany / bezlitosny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gern', 'gern', null, 'other', null, 'chętnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schnellstmöglich', 'schnellstmöglich', null, 'other', null, 'jak najszybciej', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('viel', 'viel', null, 'other', null, 'dużo / wiele', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('meist', 'meist', null, 'other', null, 'zazwyczaj / przeważnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('hübsch', 'hübsch', null, 'other', null, 'ładny / przystojny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('grau', 'grau', null, 'other', null, 'szary', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('anmutig', 'anmutig', null, 'other', null, 'pełen gracji / wdzięczny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schlank', 'schlank', null, 'other', null, 'szczupły / smukły', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('mächtig', 'mächtig', null, 'other', null, 'potężny / mocarny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('klein', 'klein', null, 'other', null, 'mały', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('hoch', 'hoch', null, 'other', null, 'wysoki / wysoko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('fein', 'fein', null, 'other', null, 'delikatny / wytworny / dobrej jakości', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('geschmeidig', 'geschmeidig', null, 'other', null, 'giętki / miękki / elastyczny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schimmernd', 'schimmernd', null, 'other', null, 'połyskujący / lśniący', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gehärtet', 'gehärtet', null, 'other', null, 'utwardzony / hartowany', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('halb', 'halb', null, 'other', null, 'pół / połowa / na wpół', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('weich', 'weich', null, 'other', null, 'miękki', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('eigenhändig', 'eigenhändig', null, 'other', null, 'własnoręcznie / osobiście', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('groß', 'groß', null, 'other', null, 'duży / wielki', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schwer', 'schwer', null, 'other', null, 'ciężki / trudny / trudno', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('tief', 'tief', null, 'other', null, 'głęboki / głęboko', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gelangweilt', 'gelangweilt', null, 'other', null, 'znudzony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('abwesend', 'abwesend', null, 'other', null, 'nieobecny / zamyślony', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gut', 'gut', null, 'other', null, 'dobry / dobrze', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('sämtlich', 'sämtlich', null, 'other', null, 'wszyscy / wszystkie bez wyjątku', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('frisch', 'frisch', null, 'other', null, 'świeży', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('lautlos', 'lautlos', null, 'other', null, 'bezgłośny / bezgłośnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schneebedeckt', 'schneebedeckt', null, 'other', null, 'pokryty śniegiem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('still', 'still', null, 'other', null, 'cichy / nieruchomy / nieruchomo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('doppelt', 'doppelt', null, 'other', null, 'podwójny', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('grausig', 'grausig', null, 'other', null, 'makabryczny / straszliwy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('direkt', 'direkt', null, 'other', null, 'bezpośredni / bezpośrednio / tuż', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unwillkürlich', 'unwillkürlich', null, 'other', null, 'mimowolny / mimowolnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('wenig', 'wenig', null, 'other', null, 'mało / niewiele', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('wir', 'wir', null, 'other', null, 'my', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ich', 'ich', null, 'other', null, 'ja', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('du', 'du', null, 'other', null, 'ty', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ihr', 'ihr', null, 'other', null, 'wy; jej / ich', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('er', 'er', null, 'other', null, 'on', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('sie', 'sie', null, 'other', null, 'ona / oni / one / ją / ich', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('es', 'es', null, 'other', null, 'ono / to / podmiot bezosobowy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('sich', 'sich', null, 'other', null, 'się / siebie / sobie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('man', 'man', null, 'other', null, 'ktoś / ludzie / się / bezosobowo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('mein', 'mein', null, 'other', null, 'mój', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dein', 'dein', null, 'other', null, 'twój', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('sein', 'sein', null, 'other', null, 'jego / swój', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unser', 'unser', null, 'other', null, 'nasz', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dieser', 'dieser', null, 'other', null, 'ten / ta / to', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('welcher', 'welcher', null, 'other', null, 'który / jaki', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('jeder', 'jeder', null, 'other', null, 'każdy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('mancher', 'mancher', null, 'other', null, 'niejeden / niektórzy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('alle', 'alle', null, 'other', null, 'wszyscy / wszystko / wszystkie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('einige', 'einige', null, 'other', null, 'niektórzy / kilka / nieco', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('kein', 'kein', null, 'other', null, 'żaden / nie / ani jeden', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('niemand', 'niemand', null, 'other', null, 'nikt', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('etwas', 'etwas', null, 'other', null, 'coś / trochę', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('irgendetwas', 'irgendetwas', null, 'other', null, 'coś / cokolwiek', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nichts', 'nichts', null, 'other', null, 'nic', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('was', 'was', null, 'other', null, 'co / to, co', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('der', 'der', null, 'other', null, 'ten / ta / to / który; często bez tłumaczenia', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ein', 'ein', null, 'other', null, 'jakiś / pewien / jeden; często bez tłumaczenia', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('im', 'im', null, 'other', null, 'w', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('zum', 'zum', null, 'other', null, 'do / ku', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('beim', 'beim', null, 'other', null, 'przy / podczas', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ins', 'ins', null, 'other', null, 'do / w', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('am', 'am', null, 'other', null, 'przy / na / w', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('als', 'als', null, 'other', null, 'kiedy / gdy / jako / niż / jakby', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('wenn', 'wenn', null, 'other', null, 'jeśli / kiedy / gdy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dass', 'dass', null, 'other', null, 'że', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('und', 'und', null, 'other', null, 'i / a', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('oder', 'oder', null, 'other', null, 'lub / albo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('aber', 'aber', null, 'other', null, 'ale / jednak', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('doch', 'doch', null, 'other', null, 'jednak / ale / przecież', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('bevor', 'bevor', null, 'other', null, 'zanim', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('während', 'während', null, 'other', null, 'podczas gdy / podczas', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('wie', 'wie', null, 'other', null, 'jak', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('um', 'um', null, 'other', null, 'wokół / o / żeby', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('zu', 'zu', null, 'other', null, 'do / zbyt / znacznik bezokolicznika', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('mit', 'mit', null, 'other', null, 'z', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('über', 'über', null, 'other', null, 'nad / przez / o / ponad', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('in', 'in', null, 'other', null, 'w / do', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('an', 'an', null, 'other', null, 'przy / na / do', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('von', 'von', null, 'other', null, 'od / z / o / przez', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nach', 'nach', null, 'other', null, 'po / do / ku', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('vor', 'vor', null, 'other', null, 'przed', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('auf', 'auf', null, 'other', null, 'na', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unter', 'unter', null, 'other', null, 'pod / wśród', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('seit', 'seit', null, 'other', null, 'od', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('hinter', 'hinter', null, 'other', null, 'za', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('bei', 'bei', null, 'other', null, 'przy / u / w przypadku', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('bis', 'bis', null, 'other', null, 'do / aż do', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('aus', 'aus', null, 'other', null, 'z / ze środka', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('durch', 'durch', null, 'other', null, 'przez', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('neben', 'neben', null, 'other', null, 'obok', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nur', 'nur', null, 'other', null, 'tylko / jedynie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('darauf', 'darauf', null, 'other', null, 'na to / na tym / do tego', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nicht', 'nicht', null, 'other', null, 'nie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('schon', 'schon', null, 'other', null, 'już', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('so', 'so', null, 'other', null, 'tak / taki / tak bardzo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('denn', 'denn', null, 'other', null, 'właściwie / zatem / bo', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dann', 'dann', null, 'other', null, 'wtedy / potem / w takim razie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('genug', 'genug', null, 'other', null, 'dość / wystarczająco', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('auch', 'auch', null, 'other', null, 'też / również', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nie', 'nie', null, 'other', null, 'nigdy', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('selbst', 'selbst', null, 'other', null, 'nawet / sam', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('noch', 'noch', null, 'other', null, 'jeszcze / nadal', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('vielleicht', 'vielleicht', null, 'other', null, 'może / być może', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('kaum', 'kaum', null, 'other', null, 'ledwie / prawie nie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('wieder', 'wieder', null, 'other', null, 'znowu / ponownie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('fast', 'fast', null, 'other', null, 'prawie / niemal', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('darüber', 'darüber', null, 'other', null, 'o tym / nad tym / z tego', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('inzwischen', 'inzwischen', null, 'other', null, 'tymczasem / w międzyczasie / od tego czasu', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('heute', 'heute', null, 'other', null, 'dzisiaj', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('zuvor', 'zuvor', null, 'other', null, 'wcześniej / przedtem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('her', 'her', null, 'other', null, 'stamtąd / w tę stronę', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('zurück', 'zurück', null, 'other', null, 'z powrotem / wstecz', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('besonders', 'besonders', null, 'other', null, 'szczególnie / zwłaszcza', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('allzu', 'allzu', null, 'other', null, 'zbyt / nazbyt', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('zumindest', 'zumindest', null, 'other', null, 'przynajmniej', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('mal', 'mal', null, 'other', null, 'kiedyś / raz / czasem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('wohl', 'wohl', null, 'other', null, 'chyba / zapewne / prawdopodobnie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ebenso', 'ebenso', null, 'other', null, 'tak samo / równie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('unterwegs', 'unterwegs', null, 'other', null, 'w drodze / w podróży', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('einmal', 'einmal', null, 'other', null, 'raz / kiedyś', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nun', 'nun', null, 'other', null, 'teraz / cóż / no więc', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('eigentlich', 'eigentlich', null, 'other', null, 'właściwie / tak naprawdę', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gerade', 'gerade', null, 'other', null, 'właśnie / akurat / prosto', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('hier', 'hier', null, 'other', null, 'tutaj', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('gleich', 'gleich', null, 'other', null, 'zaraz / tuż / taki sam', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('dran', 'dran', null, 'other', null, 'przy tym / blisko tego', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('mittlerweile', 'mittlerweile', null, 'other', null, 'tymczasem / do tego czasu / już', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('ziemlich', 'ziemlich', null, 'other', null, 'dość / dosyć / całkiem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('trotzdem', 'trotzdem', null, 'other', null, 'mimo to / jednak', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('nein', 'nein', null, 'other', null, 'nie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('paar', 'paar', null, 'other', null, 'kilka / parę', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('da', 'da', null, 'other', null, 'tam / tu', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('zwei', 'zwei', null, 'other', null, 'dwa / dwie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('vier', 'vier', null, 'other', null, 'cztery', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('acht', 'acht', null, 'other', null, 'osiem', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('neun', 'neun', null, 'other', null, 'dziewięć', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('achtzehn', 'achtzehn', null, 'other', null, 'osiemnaście', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('vierzig', 'vierzig', null, 'other', null, 'czterdzieści', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('fünfzig', 'fünfzig', null, 'other', null, 'pięćdziesiąt', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('hundert', 'hundert', null, 'other', null, 'sto', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Ser', 'Ser', null, 'other', null, 'ser / tytuł rycerski', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null),
  ('Mylord', 'Mylord', null, 'other', null, 'mój panie / milordzie', null, null, null, 'Prolog — fragment dostarczony przez użytkownika; opracowanie DE–PL 2026-09-16', null, null, null, null, null);

-- 1. Nowe hasła. `words.id` nie jest kolumną identity, więc numerujemy od
--    bieżącego maksimum; podzapytanie liczone jest raz, przed wstawieniem.
insert into public.words (id, lemma, display, article, word_type, gender, translation_pl, example_de, example_pl, cefr, source, topic, plural, aux, synonyms, ipa)
select (select coalesce(max(id), 0) from public.words)
         + row_number() over (order by p.lemma, p.word_type),
       p.lemma, p.display, p.article, p.word_type, p.gender, p.translation_pl, p.example_de, p.example_pl, p.cefr, p.source, p.topic, p.plural, p.aux, p.synonyms, p.ipa
  from fluent_study_pack p
 where not exists (
         select 1
           from public.words w
          where lower(w.lemma) = lower(p.lemma)
            and w.word_type = p.word_type
       );

-- Podsumowanie (temp table znika przy commit, więc liczymy przed nim).
select count(*)                             as hasla_w_pakiecie,
       count(w.id)                          as hasla_w_slowniku,
       count(*) filter (where w.id is null) as brakujace
  from fluent_study_pack p
  left join public.words w
    on lower(w.lemma) = lower(p.lemma)
   and w.word_type = p.word_type;

commit;
